### ISSUE TITLE
wrong containerPort in templates/statefulset.yaml

### ISSUE THREAD

**Issue by travnewmatic** [PrivateBin/helm-chart#34]
https://github.com/PrivateBin/helm-chart/blob/master/privatebin/templates/statefulset.yaml is incorrectly configured to send traffic to container port 80

your container is listening on 8080

From https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/README.md

- `-p 8080:8080` - The Nginx webserver inside the container listens on port 8080, this parameter exposes it on your system on port 8080. Be sure to use a reverse proxy for HTTPS termination in front of it in production environments.

**Comment by bdashrad** [comment]
Fixed in #35
