### ISSUE TITLE
error validating data: ValidationError(StatefulSet.spec): missing required field "serviceName" in io.k8s.api.apps.v1.StatefulSetSpec

### ISSUE THREAD

**Issue by esys** [PrivateBin/helm-chart#40]
Helm 3 expects a statefulset to have a serviceName field as per the kubernetes openAPI spec.
However, there is none in the StatefulSet template of the chart and no way to add one.

Workaround is using the `--disable-openapi-validation` flag for Helm.

See PR https://github.com/PrivateBin/helm-chart/pull/41

**Comment by bdashrad** [comment]
Resolved by #41
