### ISSUE TITLE
Dark Mode ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [PrivateBin/helm-chart#43]
Hello, 

I see a file darkstrap-0.9.3.css , how to switch this ?

**Comment by elrido** [comment]
Please have a look at the wiki page on [configuring templates](https://github.com/PrivateBin/PrivateBin/wiki/Templates#configuring-templates) over in the main project site. If you switch to any of the `bootstrap-dark` or `page` template variants, please consider also switching the [`syntaxhighlightingtheme`](https://github.com/PrivateBin/PrivateBin/wiki/Configuration#syntaxhighlightingtheme) to `sons-of-obsidian` to get a matching color scheme when displaying source code.

You can find an example configuration file at [conf.sample.php](https://raw.githubusercontent.com/PrivateBin/PrivateBin/master/cfg/conf.sample.php) and, if I understand the helm chart correctly, can attach it as conf.php via the `configs` setting:

https://github.com/PrivateBin/helm-chart/blob/afcea80e9e4249f6170078a0bd74901aaaa9cfd7/privatebin/values.yaml#L73-L75

**Comment by cvalentin-dkt** [comment]
Thx, I hadn't noticed the little trick with the bootstrap :)
