### ISSUE TITLE
Question reg. container image use

### ISSUE THREAD

**Issue by elrido** [PrivateBin/helm-chart#5]
I have to admit that I have spent most of my time with OpenShift when dealing with Kubernetes environments and am not familiar with Helm. Do I understand the [deployment.yaml](https://github.com/PrivateBin/helm-chart/blob/master/privatebin/templates/deployment.yaml#L23) correctly in that it will attach a volume for the config file, but none for the data (located in /srv/data)? Is there a way to specify that the container image should be run with `--read-only` (I made sure to [mark all paths to be written to as volumes in the Dockerfile](https://github.com/PrivateBin/docker-nginx-fpm-alpine/blob/master/Dockerfile#L66))?

**Comment by bdashrad** [comment]
It will attach a kubernetes [volume](https://kubernetes.io/docs/concepts/storage/volumes/#configmap) at the path `/srv/cfg` (https://github.com/PrivateBin/helm-chart/blob/master/privatebin/templates/deployment.yaml#L43) from a [configmap](https://github.com/PrivateBin/helm-chart/blob/master/privatebin/templates/config.yaml) that contains any files specified in `.Values.configs` (https://github.com/PrivateBin/helm-chart/blob/master/privatebin/values.yaml#L55-L57), allowing you to override the default configuration. We can explicitly set this path to be read-only.

Currently `/srv/data` is just the path in the container itself. I'd have to do some research to see what we would need to change to make sure all paths except the ones you listed are read-only.

**Comment by bdashrad** [comment]
I'm also going to open up a new issue to change from a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) to a [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/), so data on disk can persist between pod restarts if desired.

**Comment by elrido** [comment]
Sorry, I meant this differently: The image in question can be run in read-only mode, optional, not required, but good for security and maybe also has minimal performance benefits, depending on the storage driver used in the kubernetes setup. The Dockerfile marked volumes will always be writable, even if nothing gets attached to them and the image is launched as read-only.

The two paths /srv/cfg and /srv/data _should_ be attached to persistent volumes and the data one _needs_ to be a writeable one as that is where the instance will store the pastes, comments, server salt, traffic limiter, etc. Maybe the StatefulSet will address this?

**Comment by bdashrad** [comment]
We can ensure they are attached to persistent volumes once we switch to a StatefulSet. We can't ensure that the correct volumes would always be available in the Deployment configuration.

Would `/srv/cfg` ever be changed by the app itself? If not, I'd leave it read-only on start, and only let users change the configuration by updating the ConfigMap values. Configuration settings set in Values.yaml for the ConfigMap would persist between restarts.

**Comment by elrido** [comment]
Thank you for the clarifications. All my questions got answered.

Yes, you are correct, the /srv/cfg directory can be attached read-only as well. The applications should never change this file under normal circumstances. The only exception to this was the 1.1.1 release, where we would attempt to convert old .ini files automatically to php. We did [document how the change could be performed manually](https://privatebin.info/news/v1.1.1-release.html), though.
