### ISSUE TITLE
initContainer fails when using StatefulSet option

### ISSUE THREAD

**Issue by reg0bs** [PrivateBin/helm-chart#54]
The initContainer for setting permissions runs the following command:

```
command:
  - chown
  - -R
  - "65534:82"
  - /srv/cfg
``` 

The problem with this is the configMap being mounted as well and the permissions of mounted configMaps can not be changed this way. This means that chown logs some warnings to the console and exits with exit code 1. Exit code 1 means that the container was not successful and is therefore received by k8s as it would fail, resulting in CrashLoops.

To overcome this issue I changed the command to this and added args:
```
  command: ["/bin/sh","-c"]
  args: ["chown -R 65534:82 /srv/cfg || :"]
```
The double pipe and the semicolon force the command to always return true, which will allow sh to return an exit code of 0.

If you accept this solution I can create a PR if you like.

Thanks!

**Comment by reg0bs** [comment]
If I think about it...what should this initContainer achieve anyway? 
Why should the configuration be changed to be owned by 65534?

I am running this as nobody and the app seems to work just fine even when the folders are owned by root.

**Comment by elrido** [comment]
I think we are pointing the init container at the wrong volume. It's purpose is to adjust the permissions of the storage volume, so the main container can write to it using the UID/GID defined for it. The configurations should remain read-only to others and owned by root.

**Comment by dbodencnve** [comment]
I tried to deploy using the changes made in https://github.com/PrivateBin/helm-chart/commit/492ac592062af378dc52efb64d0228c71b35b128 but the init container goes into a crash loop.

```
chown: /mnt/lost+found: Operation not permitted
chown: /mnt/lost+found: Operation not permitted
chown: /mnt: Operation not permitted
chown: /mnt: Operation not permitted  
```

**Comment by reg0bs** [comment]
Mounted volumes should already have the correct permissions, that is what the `fsGroup` option is for.

**Comment by elrido** [comment]
Thank you for explaining this, I've not been aware of this security context option and still been using init containers in my deployments to chown all my volumes. I've updated the PR accordingly and also [raised one for the container images readme file](https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/82).
