### ISSUE TITLE
Chart 0.10.x broken in OpenShift Kubernetes because of 'readOnlyRootFileSystem'

### ISSUE THREAD

**Issue by m-wack** [PrivateBin/helm-chart#60]
Hello, I just made the update from chart 0.8.0 to 0.10.1 in our OpenShift Kubernetes Environment. I am using the :latest image tag.

However, due to the new 'readOnlyRootFileSystem' = true, setting brought to the chart, the pod will not start anymore.
Setting 'readOnlyRootFileSystem' to false, solves the following error:

```
cp: can't create directory '/run/services': Read-only file system
s6-svscan: fatal: unable to chdir: No such file or directory
```

I saw the Dockerfile of the image is using the 'VOLUME' command e.g. for /run. However this does not seem to help in K8s. 
Maybe some sort of mount for /run, etc... needs to be incorporated for it to work? 

An easy fix would be to allow disabling the 'readOnlyRootFileSystem' via values.yaml.

**Comment by m-wack** [comment]
@elrido any change of getting this fixes from the readonlyroot branch released into the official chart?

**Comment by elrido** [comment]
I had tried to include a solution for this in #78 and we still need the project maintainer to review it - I don't have that permission.
