### ISSUE TITLE
Support replicaCount when using StatefulState

### ISSUE THREAD

**Issue by Socolin** [PrivateBin/helm-chart#61]
Hello,

Can you add `replicas` for `controller.kind=StatefulSet` in the [template](https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/templates/statefulset.yaml#L16) according to the [documentation](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/) like what is available for Deployment) it should be supported

Like what is already done for Deployment
https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/templates/deployment.yaml#L17

**Comment by bdashrad** [comment]
Sure, I can do this
