### ISSUE TITLE
Privatebin version 0.9.x does not work with GCE ingress <1.21.3-gke.1600

### ISSUE THREAD

**Issue by franeksaww** [PrivateBin/helm-chart#62]
Hi!

 Hardcoded pathType is blocking newest releases with networking.k8s.io/v1 on GKE. This is important as networking.k8s.io/v1beta1 API will be removed soon.

Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported

@bdashrad FYI

**Comment by bdashrad** [comment]
@franeksaww Could you provide some documentation for why setting `pathType: Prefix` here won't work? We already do a conditional check to use the appropriate networking.k8s.io api version https://github.com/PrivateBin/helm-chart/blob/master/charts/privatebin/templates/ingress.yaml#L10-L16

**Comment by franeksaww** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#creating_an_ingress
`
For GKE clusters running versions earlier than 1.21.3-gke.1600, the only supported value for the pathType field is ImplementationSpecific. For clusters running version 1.21.3-gke.1600 or later, Prefix and Exact values are also supported for pathType.`

**Comment by bdashrad** [comment]
Thank you for that!
