### ISSUE TITLE
Update helm chart to use 1.5.1

### ISSUE THREAD

**Issue by dmitry-mightydevops** [PrivateBin/helm-chart#84]
https://github.com/PrivateBin/helm-chart/blob/a3ae8f1d42396aa45e8de1cb3aadb62045d695c9/charts/privatebin/Chart.yaml#L3

```
➜ helm search repo private              
NAME                         	CHART VERSION	APP VERSION	DESCRIPTION                                       
privatebin/privatebin        	0.17.0       	1.3.5      	A Helm chart for installing PrivateBin            
```

**Comment by elrido** [comment]
I think we need some additional maintainers for this project - I don't use helm myself and am not familiar with it. If anyone would like to step up and support @bdashrad in keeping this git repo up to date, please do reach out to me or say so here or in a new issue.

If it is indeed appropriate to update that value every time we release PrivateBin, I'm happy to add that as a [step to the release process](https://github.com/PrivateBin/PrivateBin/wiki/Release-Checklist) to raise a pull request in here, too, but would appreciate if it were approved/merged by someone that is familiar with the tool.

**Comment by bdashrad** [comment]
@elrido I try to update when I notice releases, but sometimes I don't get a github notification. As I mentioned above, we don't have to update the helm chart for users to change their PrivateBin version as well, so this shouldn't be blocking anyone.

**Comment by elrido** [comment]
Thank you for the guidance, I've update the checklist and will raise a pull request for this from now on. Cheers!
